services:
  - type: web
    name: polissage-php
    env: php
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      mkdir -p public/images
      python python/init_data.py
    startCommand: php -S 0.0.0.0:$PORT -t public
    envVars:
      - key: PHP_VERSION
        value: "8.1"
    autoDeploy: true
    previewsEnabled: true
